/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Acer
 */
public class English extends javax.swing.JFrame {

    /**
     * Creates new form English
     */
    public English() {
        initComponents();
        jLabel7.setText("");
        jPanel18.setVisible(false);
        jPanel19.setVisible(false);
        jPanel20.setVisible(false);
        jTextArea2.setEditable(false);
        jTextArea3.setEditable(false);
        jTextArea1.setEditable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(54, 33, 89));
        sidePanel.setLayout(new java.awt.GridLayout(14, 1));

        jPanel7.setBackground(new java.awt.Color(2, 55, 91));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(2, 55, 91));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Small", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(225, 51, 64));
        jLabel2.setText("External Environment factors");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 240, 30));

        sidePanel.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(2, 55, 91));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Small", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(225, 51, 64));
        jLabel3.setText("of a private University in Albania");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 42));

        sidePanel.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(2, 55, 91));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(jPanel10);

        jPanel4.setBackground(new java.awt.Color(54, 33, 89));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(189, 43, 54));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("      Economic Landscape");
        jButton4.setActionCommand("         Economic Landsace");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 40));

        sidePanel.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(83, 56, 133));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(189, 43, 54));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("      Regulatory Environment");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 40));

        sidePanel.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(83, 56, 133));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(189, 43, 54));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("      Societal Factors");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 290, 40));

        sidePanel.add(jPanel5);

        jPanel11.setBackground(new java.awt.Color(2, 55, 91));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(2, 55, 91));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(2, 55, 91));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("For more information...");
        jPanel13.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 190, 24));

        sidePanel.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(2, 55, 91));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(225, 51, 64));
        jLabel5.setText("http://www.luarasi-univ.edu.al/");
        jPanel14.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Visit");
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        sidePanel.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(2, 55, 91));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(2, 55, 91));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        sidePanel.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(2, 55, 91));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(189, 43, 54));
        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, -1));

        sidePanel.add(jPanel17);

        jPanel1.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 490));

        jPanel2.setBackground(new java.awt.Color(43, 100, 138));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Stencil", 3, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(223, 223, 223));
        jLabel9.setText("WELCOME");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 260, 190));

        jLabel7.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(232, 232, 232));
        jLabel7.setText("Tekstet sipas rradhes");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 360, 60));

        jPanel3.setBackground(new java.awt.Color(189, 43, 54));

        jLabel1.setBackground(new java.awt.Color(189, 43, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\English\\src\\icons\\download.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(3, 3, 3))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 530, -1));

        jPanel20.setBackground(new java.awt.Color(43, 100, 138));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Sitka Subheading", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(232, 232, 232));
        jLabel8.setText("Meritocracy");
        jPanel20.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 110, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea3.setBackground(new java.awt.Color(232, 59, 80));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jTextArea3.setText("Meritocracy ensures that the most qualified faculty members are\nrecruited, and that they are subsequently treated fairly\nwith regard to their promotions, bonuses and other benefits. \nA university that does not adhere to meritocracy does not \nattract and retain innovative and highly competent people, \nand instead, sends them to its local, regional, or international \ncompetitors. Meritocracy is not likely to be achieved \nwithout transparency and shared governance. \nThe levels of meritocracy and transparency can be reflected \nby the corruption perception index (CPI) calculated by\nTransparency International (TI).");
        jTextArea3.setToolTipText("");
        jScrollPane3.setViewportView(jTextArea3);

        jPanel20.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 420, 180));

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel19.setBackground(new java.awt.Color(43, 100, 138));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(50, 117, 161));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("\"Luarasi\" activities");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 30));

        jButton10.setBackground(new java.awt.Color(50, 117, 161));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Academic Freedom");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 220, -1));

        jButton11.setBackground(new java.awt.Color(50, 117, 161));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Government role");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 220, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(63, 149, 206));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Sitka Small", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\n\n\nEach organization operates \nin a landscape of laws and\nregulations which determine \nwhat you can and cannot do. ");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel19.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 280, 250));

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 530, 360));

        jPanel18.setBackground(new java.awt.Color(43, 100, 138));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(50, 117, 161));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("GDP");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 42, 171, -1));

        jButton6.setBackground(new java.awt.Color(50, 117, 161));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Tuition payments");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 86, 260, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");

        jTextArea2.setBackground(new java.awt.Color(43, 100, 138));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jTextArea2.setText("Your external economic environment determines \nwhether people have money to spend and how \nwilling they are to spend it. Consumer optimism \nabout the economy is influential in generating \nconsumer spending, and fear of economic i\nnstability prompts them to hang onto their money.");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel18.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 470, 130));

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 510, 280));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel7.setText("   Economic Landscape");
        jPanel18.setVisible(true);
        jLabel9.setVisible(false);
        jPanel19.setVisible(false);
        jPanel20.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLabel7.setText("Regulatory Environment");
        jPanel18.setVisible(false);
        jPanel19.setVisible(true);
        jLabel9.setVisible(false);
        jPanel20.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jLabel7.setText("     Cultural Factors");
        jPanel20.setVisible(true);

        jPanel18.setVisible(false);
        jPanel19.setVisible(false);
        jLabel9.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextArea2.setText("In times of economic growth more people will\nlean on private universities, which means \nhigher income. GDP may, therefore, be a \nsignificant factor affecting the quality of \nuniversities. In fact, it was observed that the \nnumber of top ranked universities per country \ndepended on the country’s GDP.");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextArea2.setText("A private university generates income in \ndifferent ways. All universities, even the most \nwealthy, depend on external elements for \nfinancial survival, including tuition payments \nprovided by students and their families, funds \nfrom the government for operating expenses, \nresearch and training grants and contracts \nfrom a range of external agencies, charitable \ndonations from alumni and foundations, and \nincome-generating projects. “Luarasi” university \nis no different.Academic study is increasingly \nseen as a private good–something that mainly\nbenefits the individual and should be paid for \nby the individual.\n");

// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextArea1.setText("KU “Luarasi” is a nonprivate i\nnstitution of high education that \nexercises its activity on education \nfield, Scientific research and \ncreative activities. It’s mission is \nto create , develop, forward and \nprotect knowledge through \nteaching, scientific research and \nalso to promote arts, physical \neducation and sports.\nTo offer equal possibilities, so \nthat anyone can profit. To integrate \nteaching with scientific research. \nTo promote internation cooperation \non high education field.");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jTextArea1.setText("\n\nHigh education institutions operate \non terms of academic freedom. It \nis granted through the right:\nA.To organize teaching activities, \nscientific research, inovations, \nand creative activities.\nB.To design and develop studying \nprograms\nC.To organize the process of \nacademic staff promotion. \n");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        jTextArea1.setText("A.The government exercises\n regulatory and creative f\nunctions and finances high \neducation and scientific research.\nB.Guarantees the autonomy \nand academic freedom\nC.Responsible for determining \nand monitoring of high education \nstandards\nD.Evaluates the quality and \nfunctionality of these eduactions t\nhrough its agencies.\nE.High education institutions \nmaintain political neutrality\n");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(English.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new English().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
